### ISSUE TITLE
 Files remain in queue when opened but not read

### ISSUE THREAD

**Issue by observingClouds** [observingClouds/slkspec#15]
Some of the current tests load files from the mock-up tape archive but do not read them. As a consequence `self._cache_files()` is never called and as such `self._file_queue.get()` and `self._file_queue.task_done()`. Those files remain in the queue and cause problems in other tests.

`test_reading_dataset` cannot be currently called after calling `test_ro_mode`

Opening files in a context-manager is probably a good idea, but we might also want to have a way to reset the queue or only process the part of the queue, that we are actually requesting.

**Comment by antarcticrainforest** [comment]
I think that should be closed now, am I right?
