### ISSUE TITLE
Retrieved files not found

### ISSUE THREAD

**Issue by observingClouds** [observingClouds/slkspec#29]
There is currently [an issue with SLK/pyslk](https://gitlab.dkrz.de/hsm-tools/pyslk/-/issues/49) so that the retrievals are saved at a different spot than previously/expected.
Currently both slkspec and slk create subdirectories. Retrieved files end up in directories like `<SLK_CACHE>/arch/path/to/file/arch/path/to/file/file`

When the expected behaviour is clarified upstream, `slkspec` will be adjusted if needed.

**Comment by neumannd** [comment]
@observingClouds I'll have a look into this.

**Comment by florianziemen** [comment]
I think the new behavior of slk should be considered as 'correct', and slkspec should start requesting everything 'into' the cache dir, and let slk distribute things. That would save us from splitting up retrievals by directory, and push that whole game down in the stack.
(for reasons of sticky bits and friends, we still have to create the directories, though).

**Comment by observingClouds** [comment]
Yes, I started implementing this in https://github.com/observingClouds/slkspec/pull/32. There are some issues that need to be resolved though.

**Comment by observingClouds** [comment]
This has been addressed upstream.
