### ISSUE TITLE
Combining retrievals from different subdirectories

### ISSUE THREAD

**Issue by observingClouds** [observingClouds/slkspec#9]
Currently, retrievals from different subdirectories are not combined. Initially this was done because an older version of `slk` did not create subdirectories locally. This has been changed in `slk` to allow more efficient retrievals. `slkspec` should reflect these changes, so that independent of the directory, retrievals can be merged.

The following code can be used as a test:
```python
import xarray as xr
xr.open_mfdataset("slk:///arch/mh0010/m300408/showcase/dataset.zarr", engine="zarr")
```

Currently the output looks like the following:
```
# /scratch/m/m300408/arch/mh0010/m300408/showcase/dataset.zarr/.zmetadata
# /scratch/m/m300408/arch/mh0010/m300408/showcase/dataset.zarr/time/0
# slk search '{"$and":[{"path":{"$gte":"/arch/mh0010/m300408/showcase/dataset.zarr/time","$max_depth":1}},{"resources.name":{"$regex":"0"}}]}'
# /scratch/m/m300408/arch/mh0010/m300408/showcase/dataset.zarr/time/0
# /scratch/m/m300408/arch/mh0010/m300408/showcase/dataset.zarr/lat/0
# slk search '{"$and":[{"path":{"$gte":"/arch/mh0010/m300408/showcase/dataset.zarr/lat","$max_depth":1}},{"resources.name":{"$regex":"0"}}]}'
# /scratch/m/m300408/arch/mh0010/m300408/showcase/dataset.zarr/lon/0
# slk search '{"$and":[{"path":{"$gte":"/arch/mh0010/m300408/showcase/dataset.zarr/lon","$max_depth":1}},{"resources.name":{"$regex":"0"}}]}'
# /scratch/m/m300408/arch/mh0010/m300408/showcase/dataset.zarr/time/0
```

**Comment by antarcticrainforest** [comment]
Same here, see my coment in #10 .

**Comment by observingClouds** [comment]
No, we just need to get rid of this loop then it should work (except for`.zmetadata`):
https://github.com/observingClouds/slkspec/blob/d027825ac8da2b498c808a13652015685bdefe35/slkspec/core.py#L143

According to @naumannd slk supports retrievals across directories now.
